// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEzYSl4x1Eh5KmChhoATrQEg6n-hPV_ac',
    appId: '1:961507831676:web:dd8982ff49ceadbb293ef9',
    messagingSenderId: '961507831676',
    projectId: 'smartkit-a245a',
    authDomain: 'smartkit-a245a.firebaseapp.com',
    storageBucket: 'smartkit-a245a.firebasestorage.app',
    measurementId: 'G-LQ0NXNHJ5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGvBDxWfsI46B9uirNjzNPToRRs6giR5c',
    appId: '1:961507831676:android:b7966fa4c0249724293ef9',
    messagingSenderId: '961507831676',
    projectId: 'smartkit-a245a',
    storageBucket: 'smartkit-a245a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmsqxVIIqzTmK8WZuK0qLP6ndOZWeqVSs',
    appId: '1:961507831676:ios:3f20c4b28a7ebcad293ef9',
    messagingSenderId: '961507831676',
    projectId: 'smartkit-a245a',
    storageBucket: 'smartkit-a245a.firebasestorage.app',
    iosBundleId: 'com.example.smartkit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEzYSl4x1Eh5KmChhoATrQEg6n-hPV_ac',
    appId: '1:961507831676:web:201c59b8396ecbb5293ef9',
    messagingSenderId: '961507831676',
    projectId: 'smartkit-a245a',
    authDomain: 'smartkit-a245a.firebaseapp.com',
    storageBucket: 'smartkit-a245a.firebasestorage.app',
    measurementId: 'G-28ZN12EKH8',
  );
}
